name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Version
      description: "Version number, or commit hash if on dev branch"
      placeholder: "1.3.0 or dev@abc1234"
    validations:
      required: true

  - type: dropdown
    id: branch
    attributes:
      label: Branch
      options:
        - main
        - dev
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Drag and drop images here
