name: "V2 Bug Report"
description: "Report a bug in Teamarr V2 (alpha)"
title: "[V2 Bug]: "
labels: ["bug", "v2"]
body:
  - type: markdown
    attributes:
      value: |
        **This form is for V2 (alpha) issues only.** For V1 issues, use the regular bug report form.

  - type: input
    id: version
    attributes:
      label: Version
      description: "Docker image tag or commit hash"
      placeholder: "v2-alpha or v2-alpha@abc1234"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      options:
        - Team EPG Generation
        - Event EPG Generation
        - Stream Matching
        - Channel Management
        - Dispatcharr Integration
        - UI/Frontend
        - API
        - Database
        - Docker/Deployment
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Paste relevant logs (check container logs with `docker logs teamarr`)"
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Drag and drop images here
